pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Travis CI - Pull Request
      - approved-reviews-by=fabrice404
    actions:
      merge:
        method: merge
